package com.karlomaricevic.bluetoothmessagingapp.feature.addDevice.resolvers.models

enum class AddDeviceScreenStringKeys {
    MAKE_DEVICE_VISIBLE_MESSAGE,
    BLUETOOTH_DEVICES_TITLE,
    START_SEARCH_BUTTON,
    NO_DEVICES_NEARBY,
    BACK_CONTENT_DESCRIPTION,
    DEFAULT_ICON_CONTENT_DESCRIPTION,
    MAKE_DEVICE_VISIBLE_ERROR_TITLE,
    MAKE_DEVICE_VISIBLE_ERROR_MESSAGE,
    CONNECTING_TO_DEVICE_ERROR_TITLE,
    CONNECTING_TO_DEVICE_ERROR_MESSAGE,
    DIALOG_CONFIRM_BUTTON,
}